export const CUSTOM_KEYS = {
    BLANK_SCREEN: 0,
    MUTE: 1,
    ASPECT_RATIO: 3,
    SOURCE: 4,
    AUTO_IMAGE: 5,
    FREEZE_SCREEN: 6,
    SOURCE_INFO: 8,
    PROJECTOR_INFO: 10,
    OVERSCAN: 14,
    AV_MUTE: 15,
    CLOSED_CAPTIONS: 16,
    SPLIT_SCREEN: 17
};